name: runtime

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Work Item Title
        run:
          echo "Hello World" > test.html
          python -m http.server 8080
